Svetlina/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Svetlina.Data.Common;
using Svetlina.Data.Models;
using Svetlina.Services;

namespace Svetlina.Controllers
{

    public class ProductsController : Controller
    {
        private readonly ProductContext productContext;
        private readonly CustomerContext CustomerContext;

        public ProductsController(ProductContext productContext, CustomerContext customerContext)
        {
            this.productContext = productContext;
            this.CustomerContext = customerContext;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await productContext.ReadAllAsync(true));
        }

        // GET: Products/Details/5

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await productContext.ReadAsync((int)id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        [Authorize(Roles = "Administrator")]

        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="Administrator")]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,Price,ProductImage")] Product product)
        {
            if (ModelState.IsValid)
            {
                await productContext.CreateAsync(product);
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize(Roles = "Administrator")]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await productContext.ReadAsync((int)id,true);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]


        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,Price,ProductImage")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   
                    await productContext.UpdateAsync(product);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "Administrator")]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await productContext.ReadAsync((int)id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            

            await productContext.DeleteAsync((int)id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Addtocart(int id)
        {
            Customer user = await CustomerContext.ReadAsync(User.FindFirstValue(ClaimTypes.NameIdentifier), true);
            var product = await productContext.ReadAsync(id,true);
            user.cart.Products.Add(product);
            await CustomerContext.UpdateAsync(user,true);
            return RedirectToAction(nameof(Index));
            

        }

        private async Task<bool> ProductExists(int id)
        {
            return await productContext.ReadAsync(id) != null;
        }
    }
}

Svetlina/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Svetlina.Data.Common;
using Svetlina.Data.Models;
using Svetlina.Services;

namespace Svetlina.Controllers
{
    public class ReportsController : Controller
    {
        private readonly ReportContext reportContext;

        public ReportsController(ReportContext reportContext)
        {
            this.reportContext = reportContext;
        }

        // GET: Reports
        public async Task<IActionResult> Index()
        {
            return View(await reportContext.ReadAllAsync());
        }

        // GET: Reports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var report = await reportContext.ReadAsync((int)id, true);
            if (report == null)
            {
                return NotFound();
            }

            return View(report);
        }

        // GET: Reports/Create
        public IActionResult Create()
        {
        
            return View();
        }

        // POST: Reports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReportId,ReportName,Content,DateCreated,CustomerId")] Report report)
        {
            if (ModelState.IsValid)
            {
                await reportContext.CreateAsync(report);
                return RedirectToAction(nameof(Index));
            }
            
            return View(report);
        }

        // GET: Reports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var report = await reportContext.ReadAsync((int)id,true);
            if (report == null)
            {
                return NotFound();
            }
          
            return View(report);
        }

        // POST: Reports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReportId,ReportName,Content,DateCreated,CustomerId")] Report report)
        {
            if (id != report.ReportId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    
                    await reportContext.UpdateAsync(report);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await ReportExists(report.ReportId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
           return View(report);
        }

        // GET: Reports/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var report = await reportContext.ReadAsync((int)id); 
            if (report == null)
            {
                return NotFound();
            }

            return View(report);
        }

        // POST: Reports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            

            await reportContext.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> ReportExists(int id)
        {
            return await reportContext.ReadAsync(id) != null;
        }
    }
}

Svetlina/Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Svetlina.Data.Common;
using Svetlina.Data.Models;
using Svetlina.Services;

namespace Svetlina.Controllers
{
    public class WorkersController : Controller
    {
        private readonly WorkerContext workerContext;
        private readonly ProjectContext projectContext;

        public WorkersController(WorkerContext workerContext,ProjectContext projectContext)
        {
           this.workerContext = workerContext;  
            this.projectContext = projectContext;
        }

        //GET: Workers
        public async Task<IActionResult> Index()
        {

            return View(await workerContext.ReadAllAsync());
        }

        // GET: Workers/Details/5
        public async Task<IActionResult> Details(int? id)
        {   

            if (id == null)
            {
                return NotFound();
            }

            var worker = await workerContext.ReadAsync((int)id, true);

            if (worker == null)
            {
                return NotFound();
            }
            await LoadNav();
            return View(worker);
        }

        // GET: Workers/Create
        public async Task<IActionResult> Create()
        {
            await LoadNav();

            return View();
        }

        // POST: Workers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WorkerId,WorkerName,PhoneNumber,WorkerImage,WorkerInfo,ProjectId,SpecialisationType")] Worker worker)
        {
            if (ModelState.IsValid)
            {
                
                await workerContext.CreateAsync(worker);
                return RedirectToAction(nameof(Index));
            }
            return View(worker);
        }

        // GET: Workers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await workerContext.ReadAsync((int)id, true);
            if (worker == null)
            {
                return NotFound();
            }
            await LoadNav();

            return View(worker);
        }

        // POST: Workers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WorkerId,WorkerName,PhoneNumber,WorkerImage,WorkerInfo,ProjectId,SpecialisationType")] Worker worker)
        {
            if (id != worker.WorkerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await WorkerExists(worker.WorkerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(worker);
        }

        // GET: Workers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await workerContext.ReadAsync((int)id);
            if (worker == null)
            {
                return NotFound();
            }

            return View(worker);
        }

        // POST: Workers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            
            await workerContext.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> WorkerExists(int id)
        {
            return await workerContext.ReadAsync(id) != null; 
        }

        private async Task LoadNav()
        {
            ViewData["Projects"] = new SelectList(await projectContext.ReadAllAsync(), "ProjectId", "ProjectName");
            ViewData["SpecType"] = new SelectList(Enum.GetValues(typeof(SpecialisationType)).Cast<SpecialisationType>().ToList());
        }
    }
}

Svetlina/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -Светлина</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Svetlina.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <!--<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">-->
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow" >
            <div class="container-fluid nav-bar">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between nav-bar">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item nav-logo" >
                            <img src="~/images/Logo.png"style="height:50px; width:50px;"/>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Магазин</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Workers" asp-action="Index">Работници</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Schedules" asp-action="Index">Календар</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Index">Отзиви</a>
                        </li>
                        @if (User.IsInRole("Administrator"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Проекти</a>
                        </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main>
            @RenderBody()
        </main>
    </div>

    @*< footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Svetlina - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <footer class="site-footer "style="padding:0px">
        <div class="footer-top"style="padding:0px">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h5>Контакти</h5>
                        <ul>
                            <li><a href="tel:+359123456789">+359 123 456 789</a></li>
                            <li><a href="mailto:info@example.com">info@example.com</a></li>
                            <li><a href="#">Facebook</a></li>
                            <li><a href="#">Instagram</a></li>
                            <li><a href="#">LinkedIn</a></li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h5>Услуги</h5>
                        <ul>
                            <li><a href="#">Уеб Дизайн</a></li>
                            <li><a href="#">SEO Оптимизация</a></li>
                            <li><a href="#">Дигитален Маркетинг</a></li>
                            <li><a href="#">Съдържание</a></li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h5>Компания</h5>
                        <ul>
                            <li><a href="#">За нас</a></li>
                            <li><a href="#">Нашите проекти</a></li>
                            <li><a href="#">Сертификати</a></li>
                            <li><a href="#">Кариери</a></li>
                            <li><a href="#">Политика за поверителност</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <p class="footer-text m-0 text-center">&copy; 2024 Всички права запазени | Разработено от <a href="https://yourwebsite.com">YourWebsite</a></p>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>